

import {connectDB} from "../lib/connectDB.js";
import Food from "../model/food.js";
console.log("Connect DB : ", connectDB)
const indianFoods = [
  {
    name: "Roti (Whole Wheat)",
    calories: 71,
    protein: 2.5,
    carbs: 15,
    fat: 0.4, 
    fiber: 2,
    servingSize: 1,
    servingUnit: "piece",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Chapati",
    calories: 70,
    protein: 2.5,
    carbs: 15,
    fat: 0.5,
    fiber: 2,
    servingSize: 1,
    servingUnit: "piece",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Naan (Plain)",
    calories: 262,
    protein: 7,
    carbs: 45,
    fat: 5,
    fiber: 2,
    servingSize: 1,
    servingUnit: "piece",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Paratha (Plain)",
    calories: 126,
    protein: 3,
    carbs: 18,
    fat: 5,
    fiber: 2,
    servingSize: 1,
    servingUnit: "piece",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Aloo Paratha",
    calories: 180,
    protein: 4,
    carbs: 25,
    fat: 7,
    fiber: 3,
    servingSize: 1,
    servingUnit: "piece",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Poori",
    calories: 113,
    protein: 2,
    carbs: 14,
    fat: 6,
    fiber: 1,
    servingSize: 1,
    servingUnit: "piece",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Plain Rice (Cooked)",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    servingSize: 100,
    servingUnit: "g",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Jeera Rice",
    calories: 180,
    protein: 3,
    carbs: 30,
    fat: 5,
    fiber: 1,
    servingSize: 100,
    servingUnit: "g",
    category: "Grains",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Biryani (Veg)",
    calories: 280,
    protein: 6,
    carbs: 45,
    fat: 8,
    fiber: 3,
    servingSize: 200,
    servingUnit: "g",
    category: "Rice Dishes",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Biryani (Chicken)",
    calories: 350,
    protein: 18,
    carbs: 40,
    fat: 12,
    fiber: 2,
    servingSize: 200,
    servingUnit: "g",
    category: "Rice Dishes",
    isLocal: true,
    tags: ["indian", "high-protein"],
  },

  // Lentils & Legumes (Dal)
  {
    name: "Dal Tadka",
    calories: 110,
    protein: 6,
    carbs: 18,
    fat: 2,
    fiber: 5,
    servingSize: 150,
    servingUnit: "ml",
    category: "Lentils",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian", "high-protein"],
  },
  {
    name: "Dal Makhani",
    calories: 180,
    protein: 7,
    carbs: 20,
    fat: 8,
    fiber: 6,
    servingSize: 150,
    servingUnit: "ml",
    category: "Lentils",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Dal Fry",
    calories: 120,
    protein: 6,
    carbs: 19,
    fat: 2.5,
    fiber: 5,
    servingSize: 150,
    servingUnit: "ml",
    category: "Lentils",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Rajma Masala",
    calories: 210,
    protein: 10,
    carbs: 32,
    fat: 4,
    fiber: 8,
    servingSize: 150,
    servingUnit: "g",
    category: "Lentils",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian", "high-protein"],
  },
  {
    name: "Chana Masala",
    calories: 190,
    protein: 8,
    carbs: 28,
    fat: 5,
    fiber: 7,
    servingSize: 150,
    servingUnit: "g",
    category: "Lentils",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian", "high-protein"],
  },
  {
    name: "Sambar",
    calories: 90,
    protein: 4,
    carbs: 15,
    fat: 1.5,
    fiber: 4,
    servingSize: 150,
    servingUnit: "ml",
    category: "Lentils",
    isLocal: true,
    tags: ["vegetarian", "vegan", "south-indian"],
  },

  // Vegetables (Sabzi)
  {
    name: "Aloo Gobi",
    calories: 130,
    protein: 3,
    carbs: 20,
    fat: 4,
    fiber: 4,
    servingSize: 100,
    servingUnit: "g",
    category: "Vegetables",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Bhindi Masala",
    calories: 95,
    protein: 2,
    carbs: 12,
    fat: 4,
    fiber: 3,
    servingSize: 100,
    servingUnit: "g",
    category: "Vegetables",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Palak Paneer",
    calories: 180,
    protein: 8,
    carbs: 10,
    fat: 12,
    fiber: 3,
    servingSize: 150,
    servingUnit: "g",
    category: "Vegetables",
    isLocal: true,
    tags: ["vegetarian", "indian", "high-protein"],
  },
  {
    name: "Paneer Butter Masala",
    calories: 280,
    protein: 12,
    carbs: 15,
    fat: 20,
    fiber: 2,
    servingSize: 150,
    servingUnit: "g",
    category: "Paneer",
    isLocal: true,
    tags: ["vegetarian", "indian", "high-protein"],
  },
  {
    name: "Matar Paneer",
    calories: 200,
    protein: 10,
    carbs: 14,
    fat: 12,
    fiber: 4,
    servingSize: 150,
    servingUnit: "g",
    category: "Paneer",
    isLocal: true,
    tags: ["vegetarian", "indian", "high-protein"],
  },
  {
    name: "Aloo Matar",
    calories: 110,
    protein: 3,
    carbs: 18,
    fat: 3,
    fiber: 4,
    servingSize: 100,
    servingUnit: "g",
    category: "Vegetables",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Baingan Bharta",
    calories: 105,
    protein: 2,
    carbs: 12,
    fat: 5,
    fiber: 5,
    servingSize: 100,
    servingUnit: "g",
    category: "Vegetables",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Mix Veg Curry",
    calories: 120,
    protein: 3,
    carbs: 16,
    fat: 5,
    fiber: 4,
    servingSize: 150,
    servingUnit: "g",
    category: "Vegetables",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },

  // Paneer Dishes
  {
    name: "Paneer Tikka",
    calories: 220,
    protein: 14,
    carbs: 8,
    fat: 15,
    fiber: 1,
    servingSize: 100,
    servingUnit: "g",
    category: "Paneer",
    isLocal: true,
    tags: ["vegetarian", "indian", "high-protein"],
  },
  {
    name: "Paneer (Raw)",
    calories: 265,
    protein: 18,
    carbs: 1.2,
    fat: 20,
    fiber: 0,
    servingSize: 100,
    servingUnit: "g",
    category: "Paneer",
    isLocal: true,
    tags: ["vegetarian", "indian", "high-protein"],
  },
  {
    name: "Shahi Paneer",
    calories: 290,
    protein: 11,
    carbs: 16,
    fat: 21,
    fiber: 2,
    servingSize: 150,
    servingUnit: "g",
    category: "Paneer",
    isLocal: true,
    tags: ["vegetarian", "indian", "high-protein"],
  },

  // Chicken Dishes
  {
    name: "Chicken Curry",
    calories: 230,
    protein: 20,
    carbs: 10,
    fat: 13,
    fiber: 2,
    servingSize: 150,
    servingUnit: "g",
    category: "Chicken",
    isLocal: true,
    tags: ["indian", "high-protein"],
  },
  {
    name: "Butter Chicken",
    calories: 310,
    protein: 22,
    carbs: 12,
    fat: 20,
    fiber: 1,
    servingSize: 150,
    servingUnit: "g",
    category: "Chicken",
    isLocal: true,
    tags: ["indian", "high-protein"],
  },
  {
    name: "Chicken Tikka",
    calories: 180,
    protein: 26,
    carbs: 4,
    fat: 6,
    fiber: 0,
    servingSize: 100,
    servingUnit: "g",
    category: "Chicken",
    isLocal: true,
    tags: ["indian", "high-protein", "low-carb"],
  },
  {
    name: "Tandoori Chicken",
    calories: 190,
    protein: 28,
    carbs: 2,
    fat: 7,
    fiber: 0,
    servingSize: 100,
    servingUnit: "g",
    category: "Chicken",
    isLocal: true,
    tags: ["indian", "high-protein", "low-carb"],
  },

  // Snacks
  {
    name: "Samosa (1 piece)",
    calories: 262,
    protein: 5,
    carbs: 32,
    fat: 12,
    fiber: 3,
    servingSize: 1,
    servingUnit: "piece",
    category: "Snacks",
    isLocal: true,
    tags: ["vegetarian", "indian", "fried"],
  },
  {
    name: "Pakora (100g)",
    calories: 280,
    protein: 6,
    carbs: 28,
    fat: 16,
    fiber: 3,
    servingSize: 100,
    servingUnit: "g",
    category: "Snacks",
    isLocal: true,
    tags: ["vegetarian", "indian", "fried"],
  },
  {
    name: "Vada Pav",
    calories: 286,
    protein: 6,
    carbs: 40,
    fat: 11,
    fiber: 3,
    servingSize: 1,
    servingUnit: "piece",
    category: "Snacks",
    isLocal: true,
    tags: ["vegetarian", "indian", "street-food"],
  },
  {
    name: "Pani Puri (6 pieces)",
    calories: 240,
    protein: 4,
    carbs: 36,
    fat: 9,
    fiber: 2,
    servingSize: 6,
    servingUnit: "pieces",
    category: "Snacks",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian", "street-food"],
  },
  {
    name: "Bhel Puri",
    calories: 180,
    protein: 4,
    carbs: 28,
    fat: 6,
    fiber: 3,
    servingSize: 100,
    servingUnit: "g",
    category: "Snacks",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian", "street-food"],
  },
  {
    name: "Dhokla (2 pieces)",
    calories: 160,
    protein: 4,
    carbs: 26,
    fat: 4,
    fiber: 2,
    servingSize: 100,
    servingUnit: "g",
    category: "Snacks",
    isLocal: true,
    tags: ["vegetarian", "vegan", "indian"],
  },
  {
    name: "Kachori (1 piece)",
    calories: 185,
    protein: 4,
    carbs: 24,
    fat: 8,
    fiber: 2,
    servingSize: 1,
    servingUnit: "piece",
    category: "Snacks",
    isLocal: true,
    tags: ["vegetarian", "indian", "fried"],
  },

  // Dairy
  {
    name: "Dahi (Plain Curd)",
    calories: 60,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    servingSize: 100,
    servingUnit: "g",
    category: "Dairy",
    isLocal: true,
    tags: ["vegetarian", "probiotic"],
  },
  {
    name: "Raita (Plain)",
    calories: 50,
    protein: 2.5,
    carbs: 4,
    fat: 2.5,
    fiber: 0,
    servingSize: 100,
    servingUnit: "g",
    category: "Dairy",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Lassi (Sweet)",
    calories: 140,
    protein: 4,
    carbs: 22,
    fat: 4,
    fiber: 0,
    servingSize: 250,
    servingUnit: "ml",
    category: "Beverages",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Lassi (Salted)",
    calories: 70,
    protein: 4,
    carbs: 6,
    fat: 3,
    fiber: 0,
    servingSize: 250,
    servingUnit: "ml",
    category: "Beverages",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },

  // South Indian
  {
    name: "Idli (2 pieces)",
    calories: 78,
    protein: 2,
    carbs: 17,
    fat: 0.2,
    fiber: 1,
    servingSize: 2,
    servingUnit: "pieces",
    category: "South Indian",
    isLocal: true,
    tags: ["vegetarian", "vegan", "south-indian"],
  },
  {
    name: "Dosa (Plain)",
    calories: 133,
    protein: 4,
    carbs: 25,
    fat: 2,
    fiber: 1,
    servingSize: 1,
    servingUnit: "piece",
    category: "South Indian",
    isLocal: true,
    tags: ["vegetarian", "vegan", "south-indian"],
  },
  {
    name: "Masala Dosa",
    calories: 220,
    protein: 5,
    carbs: 35,
    fat: 6,
    fiber: 3,
    servingSize: 1,
    servingUnit: "piece",
    category: "South Indian",
    isLocal: true,
    tags: ["vegetarian", "vegan", "south-indian"],
  },
  {
    name: "Vada (2 pieces)",
    calories: 184,
    protein: 4,
    carbs: 18,
    fat: 11,
    fiber: 2,
    servingSize: 2,
    servingUnit: "pieces",
    category: "South Indian",
    isLocal: true,
    tags: ["vegetarian", "vegan", "south-indian", "fried"],
  },
  {
    name: "Upma",
    calories: 150,
    protein: 4,
    carbs: 26,
    fat: 3,
    fiber: 2,
    servingSize: 100,
    servingUnit: "g",
    category: "South Indian",
    isLocal: true,
    tags: ["vegetarian", "vegan", "south-indian"],
  },
  {
    name: "Uttapam",
    calories: 180,
    protein: 5,
    carbs: 30,
    fat: 4,
    fiber: 2,
    servingSize: 1,
    servingUnit: "piece",
    category: "South Indian",
    isLocal: true,
    tags: ["vegetarian", "vegan", "south-indian"],
  },

  // Sweets
  {
    name: "Gulab Jamun (2 pieces)",
    calories: 290,
    protein: 4,
    carbs: 45,
    fat: 11,
    fiber: 0,
    servingSize: 2,
    servingUnit: "pieces",
    category: "Sweets",
    isLocal: true,
    tags: ["vegetarian", "indian", "dessert"],
  },
  {
    name: "Rasgulla (2 pieces)",
    calories: 186,
    protein: 4,
    carbs: 40,
    fat: 1,
    fiber: 0,
    servingSize: 2,
    servingUnit: "pieces",
    category: "Sweets",
    isLocal: true,
    tags: ["vegetarian", "indian", "dessert"],
  },
  {
    name: "Jalebi (100g)",
    calories: 470,
    protein: 3,
    carbs: 70,
    fat: 20,
    fiber: 0,
    servingSize: 100,
    servingUnit: "g",
    category: "Sweets",
    isLocal: true,
    tags: ["vegetarian", "indian", "dessert"],
  },
  {
    name: "Kheer",
    calories: 180,
    protein: 5,
    carbs: 28,
    fat: 5,
    fiber: 0,
    servingSize: 150,
    servingUnit: "g",
    category: "Sweets",
    isLocal: true,
    tags: ["vegetarian", "indian", "dessert"],
  },

  // Beverages
  {
    name: "Chai (with milk & sugar)",
    calories: 60,
    protein: 2,
    carbs: 10,
    fat: 1.5,
    fiber: 0,
    servingSize: 150,
    servingUnit: "ml",
    category: "Beverages",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Masala Chai",
    calories: 65,
    protein: 2,
    carbs: 11,
    fat: 1.5,
    fiber: 0,
    servingSize: 150,
    servingUnit: "ml",
    category: "Beverages",
    isLocal: true,
    tags: ["vegetarian", "indian"],
  },
  {
    name: "Nimbu Pani (Lemonade)",
    calories: 40,
    protein: 0,
    carbs: 10,
    fat: 0,
    fiber: 0,
    servingSize: 250,
    servingUnit: "ml",
    category: "Beverages",
    isLocal: true,
    tags: ["vegan", "indian"],
  },
];

async function seedDatabase() {
  try {
    console.log("🔌 Connecting to database...");
    await connectDB();

    console.log("🗑️  Clearing existing Indian foods...");
    await Food.deleteMany({ isLocal: true });

    console.log("🌱 Seeding Indian foods...");
    const result = await Food.insertMany(
      indianFoods.map((food) => ({
        ...food,
        isVerifiedByAdmin: true,
        source: "Indian Foods Database",
      })),
    );

    console.log(`✅ Successfully seeded ${result.length} Indian foods!`);
    console.log("📊 Categories:", [
      ...new Set(indianFoods.map((f) => f.category)),
    ]);

    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
}

seedDatabase();
