import { connectDB } from "../lib/connectDB.js";
import Food from "../model/food.js";

const indianFoods = [
  {
    name: "Roti (Whole Wheat)",
    locality: "North India",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 71,
      protein: 2.5,
      carbs: 15,
      fat: 0.4,
      fiber: 2,
      sugar: 0,
    },
    minerals: { sodium: 120, potassium: 80, calcium: 10, iron: 0.5 },
    vitamins: {},
  },
  {
    name: "Chapati",
    locality: "India",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 70,
      protein: 2.5,
      carbs: 15,
      fat: 0.5,
      fiber: 2,
      sugar: 0,
    },
    minerals: { sodium: 115, potassium: 75, calcium: 12, iron: 0.6 },
    vitamins: {},
  },
  {
    name: "Naan (Plain)",
    locality: "North India",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 262,
      protein: 7,
      carbs: 45,
      fat: 5,
      fiber: 2,
      sugar: 3,
    },
    minerals: { sodium: 420, potassium: 100, calcium: 80, iron: 2 },
    vitamins: {},
  },
  {
    name: "Paratha (Plain)",
    locality: "North India",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 126,
      protein: 3,
      carbs: 18,
      fat: 5,
      fiber: 2,
      sugar: 0,
    },
    minerals: { sodium: 180, potassium: 90, calcium: 15, iron: 0.8 },
    vitamins: {},
  },
  {
    name: "Aloo Paratha",
    locality: "Punjab",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 180,
      protein: 4,
      carbs: 25,
      fat: 7,
      fiber: 3,
      sugar: 1,
    },
    minerals: { sodium: 240, potassium: 280, calcium: 20, iron: 1 },
    vitamins: {},
  },
  {
    name: "Plain Rice (Cooked)",
    locality: "India",
    servingSize: { value: 100, unit: "g" },
    nutrition: {
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fat: 0.3,
      fiber: 0.4,
      sugar: 0,
    },
    minerals: { sodium: 1, potassium: 35, calcium: 10, iron: 0.2 },
    vitamins: {},
  },
  {
    name: "Biryani (Veg)",
    locality: "Hyderabad",
    servingSize: { value: 200, unit: "g" },
    nutrition: {
      calories: 280,
      protein: 6,
      carbs: 45,
      fat: 8,
      fiber: 3,
      sugar: 2,
    },
    minerals: { sodium: 550, potassium: 250, calcium: 40, iron: 2 },
    vitamins: {},
  },
  {
    name: "Biryani (Chicken)",
    locality: "Hyderabad",
    servingSize: { value: 200, unit: "g" },
    nutrition: {
      calories: 350,
      protein: 18,
      carbs: 40,
      fat: 12,
      fiber: 2,
      sugar: 2,
    },
    minerals: { sodium: 620, potassium: 380, calcium: 45, iron: 2.5 },
    vitamins: {},
  },
  {
    name: "Dal Tadka",
    locality: "India",
    servingSize: { value: 150, unit: "ml" },
    nutrition: {
      calories: 110,
      protein: 6,
      carbs: 18,
      fat: 2,
      fiber: 5,
      sugar: 1,
    },
    minerals: { sodium: 380, potassium: 320, calcium: 30, iron: 2.5 },
    vitamins: {},
  },
  {
    name: "Dal Makhani",
    locality: "Punjab",
    servingSize: { value: 150, unit: "ml" },
    nutrition: {
      calories: 180,
      protein: 7,
      carbs: 20,
      fat: 8,
      fiber: 6,
      sugar: 2,
    },
    minerals: { sodium: 450, potassium: 380, calcium: 60, iron: 3 },
    vitamins: {},
  },
  {
    name: "Rajma Masala",
    locality: "North India",
    servingSize: { value: 150, unit: "g" },
    nutrition: {
      calories: 210,
      protein: 10,
      carbs: 32,
      fat: 4,
      fiber: 8,
      sugar: 3,
    },
    minerals: { sodium: 420, potassium: 480, calcium: 50, iron: 3.5 },
    vitamins: {},
  },
  {
    name: "Chana Masala",
    locality: "North India",
    servingSize: { value: 150, unit: "g" },
    nutrition: {
      calories: 190,
      protein: 8,
      carbs: 28,
      fat: 5,
      fiber: 7,
      sugar: 4,
    },
    minerals: { sodium: 460, potassium: 420, calcium: 45, iron: 3 },
    vitamins: {},
  },
  {
    name: "Palak Paneer",
    locality: "North India",
    servingSize: { value: 150, unit: "g" },
    nutrition: {
      calories: 180,
      protein: 8,
      carbs: 10,
      fat: 12,
      fiber: 3,
      sugar: 3,
    },
    minerals: { sodium: 380, potassium: 380, calcium: 180, iron: 2.5 },
    vitamins: { vitaminA: 4500, vitaminC: 15, vitaminK: 380 },
  },
  {
    name: "Paneer Butter Masala",
    locality: "North India",
    servingSize: { value: 150, unit: "g" },
    nutrition: {
      calories: 280,
      protein: 12,
      carbs: 15,
      fat: 20,
      fiber: 2,
      sugar: 6,
    },
    minerals: { sodium: 520, potassium: 280, calcium: 240, iron: 1.5 },
    vitamins: {},
  },
  {
    name: "Paneer (Raw)",
    locality: "India",
    servingSize: { value: 100, unit: "g" },
    nutrition: {
      calories: 265,
      protein: 18,
      carbs: 1.2,
      fat: 20,
      fiber: 0,
      sugar: 1,
    },
    minerals: { sodium: 18, potassium: 256, calcium: 480, iron: 0.2 },
    vitamins: {},
  },
  {
    name: "Butter Chicken",
    locality: "Delhi",
    servingSize: { value: 150, unit: "g" },
    nutrition: {
      calories: 310,
      protein: 22,
      carbs: 12,
      fat: 20,
      fiber: 1,
      sugar: 5,
    },
    minerals: { sodium: 640, potassium: 420, calcium: 65, iron: 2 },
    vitamins: {},
  },
  {
    name: "Chicken Tikka",
    locality: "Punjab",
    servingSize: { value: 100, unit: "g" },
    nutrition: {
      calories: 180,
      protein: 26,
      carbs: 4,
      fat: 6,
      fiber: 0,
      sugar: 2,
    },
    minerals: { sodium: 520, potassium: 380, calcium: 18, iron: 1.2 },
    vitamins: {},
  },
  {
    name: "Tandoori Chicken",
    locality: "Punjab",
    servingSize: { value: 100, unit: "g" },
    nutrition: {
      calories: 190,
      protein: 28,
      carbs: 2,
      fat: 7,
      fiber: 0,
      sugar: 1,
    },
    minerals: { sodium: 480, potassium: 420, calcium: 20, iron: 1.4 },
    vitamins: {},
  },
  {
    name: "Samosa",
    locality: "India",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 262,
      protein: 5,
      carbs: 32,
      fat: 12,
      fiber: 3,
      sugar: 2,
    },
    minerals: { sodium: 420, potassium: 180, calcium: 25, iron: 1.8 },
    vitamins: {},
  },
  {
    name: "Dosa (Plain)",
    locality: "South India",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 168,
      protein: 4,
      carbs: 28,
      fat: 4,
      fiber: 2,
      sugar: 1,
    },
    minerals: { sodium: 320, potassium: 120, calcium: 25, iron: 1.5 },
    vitamins: {},
  },
  {
    name: "Idli (2 pieces)",
    locality: "South India",
    servingSize: { value: 2, unit: "pieces" },
    nutrition: {
      calories: 78,
      protein: 2,
      carbs: 17,
      fat: 0.2,
      fiber: 1,
      sugar: 0,
    },
    minerals: { sodium: 280, potassium: 60, calcium: 12, iron: 0.5 },
    vitamins: {},
  },
  {
    name: "Vada",
    locality: "South India",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 150,
      protein: 3,
      carbs: 15,
      fat: 9,
      fiber: 2,
      sugar: 0,
    },
    minerals: { sodium: 280, potassium: 140, calcium: 18, iron: 1.2 },
    vitamins: {},
  },
  {
    name: "Curd (Plain Yogurt)",
    locality: "India",
    servingSize: { value: 100, unit: "g" },
    nutrition: {
      calories: 60,
      protein: 3.5,
      carbs: 4.7,
      fat: 3.2,
      fiber: 0,
      sugar: 4.7,
    },
    minerals: { sodium: 46, potassium: 155, calcium: 120, iron: 0.1 },
    vitamins: { vitaminB: 0.5 },
  },
  {
    name: "Raita",
    locality: "India",
    servingSize: { value: 100, unit: "g" },
    nutrition: {
      calories: 52,
      protein: 3,
      carbs: 5,
      fat: 2,
      fiber: 1,
      sugar: 4,
    },
    minerals: { sodium: 180, potassium: 140, calcium: 110, iron: 0.2 },
    vitamins: {},
  },
  {
    name: "Lassi (Sweet)",
    locality: "Punjab",
    servingSize: { value: 200, unit: "ml" },
    nutrition: {
      calories: 150,
      protein: 6,
      carbs: 24,
      fat: 3,
      fiber: 0,
      sugar: 24,
    },
    minerals: { sodium: 95, potassium: 280, calcium: 220, iron: 0.1 },
    vitamins: {},
  },
  {
    name: "Gulab Jamun (2 pieces)",
    locality: "India",
    servingSize: { value: 2, unit: "pieces" },
    nutrition: {
      calories: 175,
      protein: 3,
      carbs: 26,
      fat: 7,
      fiber: 0,
      sugar: 24,
    },
    minerals: { sodium: 85, potassium: 60, calcium: 95, iron: 0.4 },
    vitamins: {},
  },
  {
    name: "Rasgulla (2 pieces)",
    locality: "Bengal",
    servingSize: { value: 2, unit: "pieces" },
    nutrition: {
      calories: 186,
      protein: 4,
      carbs: 38,
      fat: 1,
      fiber: 0,
      sugar: 36,
    },
    minerals: { sodium: 42, potassium: 80, calcium: 140, iron: 0.2 },
    vitamins: {},
  },
  {
    name: "Kheer",
    locality: "India",
    servingSize: { value: 100, unit: "g" },
    nutrition: {
      calories: 117,
      protein: 3,
      carbs: 18,
      fat: 3.5,
      fiber: 0,
      sugar: 16,
    },
    minerals: { sodium: 48, potassium: 140, calcium: 105, iron: 0.2 },
    vitamins: {},
  },
  {
    name: "Boiled Egg",
    locality: "",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 68,
      protein: 6,
      carbs: 0.6,
      fat: 5,
      fiber: 0,
      sugar: 0.6,
    },
    minerals: { sodium: 62, potassium: 63, calcium: 25, iron: 0.6 },
    vitamins: { vitaminA: 260, vitaminB: 0.4, vitaminD: 40 },
  },
  {
    name: "Omelette (2 eggs)",
    locality: "",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 154,
      protein: 13,
      carbs: 1,
      fat: 11,
      fiber: 0,
      sugar: 1,
    },
    minerals: { sodium: 340, potassium: 145, calcium: 55, iron: 1.8 },
    vitamins: { vitaminA: 520, vitaminB: 0.8, vitaminD: 80 },
  },
  {
    name: "Banana",
    locality: "",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 105,
      protein: 1.3,
      carbs: 27,
      fat: 0.3,
      fiber: 3.1,
      sugar: 14,
    },
    minerals: { sodium: 1, potassium: 422, calcium: 6, iron: 0.3 },
    vitamins: { vitaminC: 10, vitaminB: 0.5 },
  },
  {
    name: "Apple",
    locality: "",
    servingSize: { value: 1, unit: "piece" },
    nutrition: {
      calories: 95,
      protein: 0.5,
      carbs: 25,
      fat: 0.3,
      fiber: 4.4,
      sugar: 19,
    },
    minerals: { sodium: 2, potassium: 195, calcium: 11, iron: 0.2 },
    vitamins: { vitaminC: 8, vitaminK: 4 },
  },
  {
    name: "Milk (Full Fat)",
    locality: "",
    servingSize: { value: 200, unit: "ml" },
    nutrition: {
      calories: 122,
      protein: 6.4,
      carbs: 9,
      fat: 6.4,
      fiber: 0,
      sugar: 9,
    },
    minerals: { sodium: 84, potassium: 292, calcium: 240, iron: 0.1 },
    vitamins: { vitaminA: 126, vitaminB: 0.7, vitaminD: 2 },
  },
  {
    name: "Bread (White, 2 slices)",
    locality: "",
    servingSize: { value: 2, unit: "slices" },
    nutrition: {
      calories: 160,
      protein: 5,
      carbs: 30,
      fat: 2,
      fiber: 2,
      sugar: 3,
    },
    minerals: { sodium: 320, potassium: 60, calcium: 140, iron: 2 },
    vitamins: {},
  },
  {
    name: "Peanut Butter",
    locality: "",
    servingSize: { value: 2, unit: "tbsp" },
    nutrition: {
      calories: 188,
      protein: 8,
      carbs: 7,
      fat: 16,
      fiber: 2,
      sugar: 3,
    },
    minerals: { sodium: 140, potassium: 208, calcium: 16, iron: 0.6 },
    vitamins: { vitaminE: 3 },
  },
  {
    name: "Almonds",
    locality: "",
    servingSize: { value: 28, unit: "g" },
    nutrition: {
      calories: 164,
      protein: 6,
      carbs: 6,
      fat: 14,
      fiber: 3.5,
      sugar: 1,
    },
    minerals: { sodium: 0, potassium: 208, calcium: 76, iron: 1 },
    vitamins: { vitaminE: 7.3 },
  },
  {
    name: "Cashews",
    locality: "",
    servingSize: { value: 28, unit: "g" },
    nutrition: {
      calories: 157,
      protein: 5,
      carbs: 9,
      fat: 12,
      fiber: 1,
      sugar: 2,
    },
    minerals: { sodium: 3, potassium: 187, calcium: 10, iron: 1.9 },
    vitamins: {},
  },
];

async function seedDatabase() {
  try {
    await connectDB();

    console.log("🌱 Starting food database seeding...");

    // Clear existing verified foods
    await Food.deleteMany({ "verification.verified": true });
    console.log("✅ Cleared existing verified foods");

    // Transform and insert foods
    const foodsToInsert = indianFoods.map((food) => ({
      ...food,
      verification: {
        verified: true,
        approvedBy: null,
      },
      createdBy: null,
    }));

    const result = await Food.insertMany(foodsToInsert);
    console.log(`✅ Successfully added ${result.length} foods to the database`);

    console.log("\n🎉 Food seeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
