/**
 * Seed verified exercises into the database
 * Run with: node scripts/seedExercises.js
 */

import mongoose from "mongoose";
import dotenv from "dotenv";

dotenv.config({ path: ".env" });

const MONGO_URI = process.env.MONGO_URI;

const ExerciseSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    type: {
      type: String,
      enum: ["cardio", "strength", "flexibility", "balance", "functional"],
    },
    caloriesPerMinute: Number,
    caloriesPerSet: Number,
    muscleGroups: [String],
    difficulty: {
      type: String,
      enum: ["beginner", "intermediate", "advanced"],
    },
    description: String,
    imageUrl: String,
    verification: {
      verified: { type: Boolean, default: false },
    },
    addedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true },
);

const Exercise =
  mongoose.models.Exercise || mongoose.model("Exercise", ExerciseSchema);

const exercises = [
  // ── CARDIO (25) ─────────────────────────────────────────────────────────────
  {
    name: "Running (moderate)",
    type: "cardio",
    caloriesPerMinute: 10,
    muscleGroups: ["quadriceps", "hamstrings", "calves"],
    difficulty: "beginner",
    description: "Steady-state moderate pace run.",
  },
  {
    name: "Running (fast pace)",
    type: "cardio",
    caloriesPerMinute: 13,
    muscleGroups: ["quadriceps", "hamstrings", "calves", "glutes"],
    difficulty: "intermediate",
    description: "High-tempo run above 8 km/h.",
  },
  {
    name: "Cycling (stationary)",
    type: "cardio",
    caloriesPerMinute: 8,
    muscleGroups: ["quadriceps", "glutes", "calves"],
    difficulty: "beginner",
    description: "Low-impact cardio on stationary bike.",
  },
  {
    name: "Cycling (outdoor intense)",
    type: "cardio",
    caloriesPerMinute: 12,
    muscleGroups: ["quadriceps", "glutes", "calves"],
    difficulty: "intermediate",
    description: "Vigorous outdoor cycling with varied terrain.",
  },
  {
    name: "Jump Rope",
    type: "cardio",
    caloriesPerMinute: 12,
    muscleGroups: ["calves", "core", "shoulders"],
    difficulty: "intermediate",
    description: "High-intensity skipping rope workout.",
  },
  {
    name: "Jump Rope (fast)",
    type: "cardio",
    caloriesPerMinute: 15,
    muscleGroups: ["calves", "core", "shoulders"],
    difficulty: "advanced",
    description: "Double-unders and fast-cadence skipping.",
  },
  {
    name: "Swimming (freestyle)",
    type: "cardio",
    caloriesPerMinute: 9,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Continuous freestyle laps in the pool.",
  },
  {
    name: "Swimming (breaststroke)",
    type: "cardio",
    caloriesPerMinute: 8,
    muscleGroups: ["chest", "back", "legs"],
    difficulty: "beginner",
    description: "Breaststroke swimming for full-body conditioning.",
  },
  {
    name: "HIIT Sprint Intervals",
    type: "cardio",
    caloriesPerMinute: 14,
    muscleGroups: ["quadriceps", "hamstrings", "glutes"],
    difficulty: "advanced",
    description: "Alternating high-intensity sprints with short rest.",
  },
  {
    name: "Walking (brisk)",
    type: "cardio",
    caloriesPerMinute: 5,
    muscleGroups: ["glutes", "hamstrings", "calves"],
    difficulty: "beginner",
    description: "Fast-paced walking for active recovery.",
  },
  {
    name: "Elliptical Trainer",
    type: "cardio",
    caloriesPerMinute: 7,
    muscleGroups: ["quadriceps", "glutes", "core"],
    difficulty: "beginner",
    description: "Low-impact full-body cardio machine.",
  },
  {
    name: "Rowing Machine",
    type: "cardio",
    caloriesPerMinute: 11,
    muscleGroups: ["back", "biceps", "core", "glutes"],
    difficulty: "intermediate",
    description: "Full-body cardio on the rowing machine.",
  },
  {
    name: "Stair Climbing",
    type: "cardio",
    caloriesPerMinute: 9,
    muscleGroups: ["glutes", "quadriceps", "calves"],
    difficulty: "intermediate",
    description: "Stair climber machine or actual stairs.",
  },
  {
    name: "Kickboxing Cardio",
    type: "cardio",
    caloriesPerMinute: 11,
    muscleGroups: ["core", "shoulders", "legs"],
    difficulty: "intermediate",
    description: "Cardio kickboxing combining punches and kicks.",
  },
  {
    name: "Zumba",
    type: "cardio",
    caloriesPerMinute: 7,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Dance-fitness class set to latin music.",
  },
  {
    name: "Dance Cardio",
    type: "cardio",
    caloriesPerMinute: 7,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "High-energy dance workout for cardio fitness.",
  },
  {
    name: "Water Aerobics",
    type: "cardio",
    caloriesPerMinute: 5,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Low-impact aerobic exercise in a pool.",
  },
  {
    name: "Aerobic Step Training",
    type: "cardio",
    caloriesPerMinute: 6,
    muscleGroups: ["glutes", "quadriceps", "calves"],
    difficulty: "beginner",
    description: "Step-up and step-down aerobics on a platform.",
  },
  {
    name: "Treadmill Incline Walk",
    type: "cardio",
    caloriesPerMinute: 7,
    muscleGroups: ["glutes", "calves", "hamstrings"],
    difficulty: "beginner",
    description: "Brisk walk at a 10–15% incline.",
  },
  {
    name: "Mountain Climbers",
    type: "cardio",
    caloriesPerMinute: 9,
    muscleGroups: ["core", "shoulders", "quadriceps"],
    difficulty: "intermediate",
    description: "Fast alternating knee drives in plank position.",
  },
  {
    name: "Jumping Jacks",
    type: "cardio",
    caloriesPerMinute: 7,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Classic whole-body jumping warm-up exercise.",
  },
  {
    name: "Shadow Boxing",
    type: "cardio",
    caloriesPerMinute: 9,
    muscleGroups: ["shoulders", "core", "legs"],
    difficulty: "intermediate",
    description: "Boxing movements against an imaginary opponent.",
  },
  {
    name: "Skipping (slow)",
    type: "cardio",
    caloriesPerMinute: 8,
    muscleGroups: ["calves", "core"],
    difficulty: "beginner",
    description: "Slow-paced jump rope for warm-up or beginners.",
  },
  {
    name: "Spinning Class",
    type: "cardio",
    caloriesPerMinute: 13,
    muscleGroups: ["quadriceps", "glutes", "calves"],
    difficulty: "advanced",
    description: "High-intensity stationary bike cycling class.",
  },
  {
    name: "Stair Stepper",
    type: "cardio",
    caloriesPerMinute: 8,
    muscleGroups: ["glutes", "quadriceps", "calves"],
    difficulty: "intermediate",
    description: "Stair stepper machine for leg and cardio burn.",
  },

  // ── STRENGTH (45) ────────────────────────────────────────────────────────────
  {
    name: "Barbell Back Squat",
    type: "strength",
    caloriesPerSet: 20,
    muscleGroups: ["quadriceps", "glutes", "hamstrings", "core"],
    difficulty: "intermediate",
    description: "Barbell on upper back, squat to parallel.",
  },
  {
    name: "Deadlift",
    type: "strength",
    caloriesPerSet: 22,
    muscleGroups: ["back", "glutes", "hamstrings", "core"],
    difficulty: "intermediate",
    description: "Hip-hinge lift engaging the posterior chain.",
  },
  {
    name: "Bench Press",
    type: "strength",
    caloriesPerSet: 15,
    muscleGroups: ["chest", "triceps", "shoulders"],
    difficulty: "intermediate",
    description: "Horizontal push on flat bench.",
  },
  {
    name: "Pull Ups",
    type: "strength",
    caloriesPerSet: 12,
    muscleGroups: ["back", "biceps", "core"],
    difficulty: "intermediate",
    description: "Bodyweight vertical pull for back and arm development.",
  },
  {
    name: "Overhead Press",
    type: "strength",
    caloriesPerSet: 14,
    muscleGroups: ["shoulders", "triceps", "core"],
    difficulty: "intermediate",
    description: "Standing barbell press overhead.",
  },
  {
    name: "Dumbbell Lunges",
    type: "strength",
    caloriesPerSet: 10,
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    difficulty: "beginner",
    description: "Walking or stationary lunges with dumbbells.",
  },
  {
    name: "Dumbbell Bicep Curl",
    type: "strength",
    caloriesPerSet: 7,
    muscleGroups: ["biceps"],
    difficulty: "beginner",
    description: "Isolation curl for the biceps.",
  },
  {
    name: "Tricep Dips",
    type: "strength",
    caloriesPerSet: 9,
    muscleGroups: ["triceps", "chest", "shoulders"],
    difficulty: "beginner",
    description: "Bodyweight dips on parallel bars or bench.",
  },
  {
    name: "Bent Over Row",
    type: "strength",
    caloriesPerSet: 16,
    muscleGroups: ["back", "biceps", "core"],
    difficulty: "intermediate",
    description: "Barbell or dumbbell row for mid-back.",
  },
  {
    name: "Romanian Deadlift",
    type: "strength",
    caloriesPerSet: 18,
    muscleGroups: ["hamstrings", "glutes", "back"],
    difficulty: "intermediate",
    description: "Hip-hinge focusing on hamstring stretch.",
  },
  {
    name: "Bulgarian Split Squat",
    type: "strength",
    caloriesPerSet: 15,
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    difficulty: "advanced",
    description: "Rear-elevated split squat for single-leg strength.",
  },
  {
    name: "Incline Bench Press",
    type: "strength",
    caloriesPerSet: 14,
    muscleGroups: ["chest", "triceps", "shoulders"],
    difficulty: "intermediate",
    description: "Bench press at 30–45 degree incline for upper chest.",
  },
  {
    name: "Decline Bench Press",
    type: "strength",
    caloriesPerSet: 13,
    muscleGroups: ["chest", "triceps"],
    difficulty: "intermediate",
    description: "Bench press at a decline for lower chest.",
  },
  {
    name: "Dumbbell Fly",
    type: "strength",
    caloriesPerSet: 8,
    muscleGroups: ["chest", "shoulders"],
    difficulty: "beginner",
    description: "Isolation chest movement with dumbbells.",
  },
  {
    name: "Cable Row",
    type: "strength",
    caloriesPerSet: 10,
    muscleGroups: ["back", "biceps"],
    difficulty: "beginner",
    description: "Seated cable row for mid-back thickness.",
  },
  {
    name: "Lat Pulldown",
    type: "strength",
    caloriesPerSet: 11,
    muscleGroups: ["back", "biceps"],
    difficulty: "beginner",
    description: "Cable pulldown for lat width.",
  },
  {
    name: "Leg Press",
    type: "strength",
    caloriesPerSet: 14,
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    difficulty: "beginner",
    description: "Machine-based lower body push.",
  },
  {
    name: "Leg Extension",
    type: "strength",
    caloriesPerSet: 8,
    muscleGroups: ["quadriceps"],
    difficulty: "beginner",
    description: "Machine isolation for quadriceps.",
  },
  {
    name: "Leg Curl",
    type: "strength",
    caloriesPerSet: 8,
    muscleGroups: ["hamstrings"],
    difficulty: "beginner",
    description: "Machine isolation for hamstrings.",
  },
  {
    name: "Calf Raise",
    type: "strength",
    caloriesPerSet: 5,
    muscleGroups: ["calves"],
    difficulty: "beginner",
    description: "Standing or seated calf raise.",
  },
  {
    name: "Shoulder Lateral Raise",
    type: "strength",
    caloriesPerSet: 6,
    muscleGroups: ["shoulders"],
    difficulty: "beginner",
    description: "Dumbbell lateral raise for medial deltoid.",
  },
  {
    name: "Front Raise",
    type: "strength",
    caloriesPerSet: 5,
    muscleGroups: ["shoulders"],
    difficulty: "beginner",
    description: "Dumbbell front raise for anterior deltoid.",
  },
  {
    name: "Barbell Bicep Curl",
    type: "strength",
    caloriesPerSet: 8,
    muscleGroups: ["biceps"],
    difficulty: "beginner",
    description: "Classic barbell curl for full bicep development.",
  },
  {
    name: "Hammer Curl",
    type: "strength",
    caloriesPerSet: 6,
    muscleGroups: ["biceps", "brachialis"],
    difficulty: "beginner",
    description: "Neutral-grip curl for brachialis and bicep.",
  },
  {
    name: "Preacher Curl",
    type: "strength",
    caloriesPerSet: 7,
    muscleGroups: ["biceps"],
    difficulty: "beginner",
    description: "Curl on preacher bench for peak contraction.",
  },
  {
    name: "Tricep Pushdown",
    type: "strength",
    caloriesPerSet: 6,
    muscleGroups: ["triceps"],
    difficulty: "beginner",
    description: "Cable pushdown for tricep isolation.",
  },
  {
    name: "Skull Crushers",
    type: "strength",
    caloriesPerSet: 7,
    muscleGroups: ["triceps"],
    difficulty: "intermediate",
    description: "Lying barbell extension for triceps.",
  },
  {
    name: "Close Grip Bench Press",
    type: "strength",
    caloriesPerSet: 13,
    muscleGroups: ["triceps", "chest"],
    difficulty: "intermediate",
    description: "Narrow-grip bench press targeting triceps.",
  },
  {
    name: "Arnold Press",
    type: "strength",
    caloriesPerSet: 11,
    muscleGroups: ["shoulders", "triceps"],
    difficulty: "intermediate",
    description: "Rotating dumbbell press for full shoulder development.",
  },
  {
    name: "Upright Row",
    type: "strength",
    caloriesPerSet: 9,
    muscleGroups: ["shoulders", "traps", "biceps"],
    difficulty: "intermediate",
    description: "Vertical pull to chin for shoulder and trap width.",
  },
  {
    name: "Barbell Shrugs",
    type: "strength",
    caloriesPerSet: 5,
    muscleGroups: ["traps"],
    difficulty: "beginner",
    description: "Barbell shrug for trapezius development.",
  },
  {
    name: "Face Pull",
    type: "strength",
    caloriesPerSet: 6,
    muscleGroups: ["rear deltoid", "traps", "rotator cuff"],
    difficulty: "beginner",
    description: "Cable face pull for rear delt and external rotation.",
  },
  {
    name: "Hip Thrust",
    type: "strength",
    caloriesPerSet: 12,
    muscleGroups: ["glutes", "hamstrings", "core"],
    difficulty: "beginner",
    description: "Barbell hip thrust for maximal glute activation.",
  },
  {
    name: "Glute Bridge",
    type: "strength",
    caloriesPerSet: 8,
    muscleGroups: ["glutes", "hamstrings"],
    difficulty: "beginner",
    description: "Floor-based hip extension for glutes.",
  },
  {
    name: "Good Morning",
    type: "strength",
    caloriesPerSet: 11,
    muscleGroups: ["hamstrings", "glutes", "back"],
    difficulty: "intermediate",
    description: "Hip-hinge under load for posterior chain.",
  },
  {
    name: "Sumo Deadlift",
    type: "strength",
    caloriesPerSet: 20,
    muscleGroups: ["glutes", "hamstrings", "back", "adductors"],
    difficulty: "intermediate",
    description: "Wide-stance deadlift emphasising inner thighs and glutes.",
  },
  {
    name: "Goblet Squat",
    type: "strength",
    caloriesPerSet: 14,
    muscleGroups: ["quadriceps", "glutes", "core"],
    difficulty: "beginner",
    description: "Front-loaded squat holding a dumbbell or kettlebell.",
  },
  {
    name: "Step Ups",
    type: "strength",
    caloriesPerSet: 10,
    muscleGroups: ["quadriceps", "glutes"],
    difficulty: "beginner",
    description: "Single-leg step onto a box or bench.",
  },
  {
    name: "Chest Dips",
    type: "strength",
    caloriesPerSet: 10,
    muscleGroups: ["chest", "triceps", "shoulders"],
    difficulty: "intermediate",
    description: "Parallel bar dip leaning forward for chest.",
  },
  {
    name: "T-Bar Row",
    type: "strength",
    caloriesPerSet: 15,
    muscleGroups: ["back", "biceps"],
    difficulty: "intermediate",
    description: "Landmine or T-bar row for back thickness.",
  },
  {
    name: "Seated Dumbbell Press",
    type: "strength",
    caloriesPerSet: 12,
    muscleGroups: ["shoulders", "triceps"],
    difficulty: "beginner",
    description: "Seated dumbbell shoulder press for stability.",
  },
  {
    name: "Hack Squat",
    type: "strength",
    caloriesPerSet: 16,
    muscleGroups: ["quadriceps", "glutes"],
    difficulty: "intermediate",
    description: "Machine hack squat for quad development.",
  },
  {
    name: "Hip Abduction Machine",
    type: "strength",
    caloriesPerSet: 6,
    muscleGroups: ["glutes", "hip abductors"],
    difficulty: "beginner",
    description: "Machine abduction for outer glutes and hip stabilisers.",
  },
  {
    name: "Glute Kickback",
    type: "strength",
    caloriesPerSet: 7,
    muscleGroups: ["glutes"],
    difficulty: "beginner",
    description: "Cable or bodyweight kickback for glute isolation.",
  },
  {
    name: "Push Ups",
    type: "strength",
    caloriesPerSet: 8,
    muscleGroups: ["chest", "triceps", "core"],
    difficulty: "beginner",
    description: "Classic bodyweight chest and tricep exercise.",
  },

  // ── YOGA / ASANAS (100) – type: flexibility ──────────────────────────────────
  {
    name: "Tadasana (Mountain Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["core", "legs"],
    difficulty: "beginner",
    description: "Standing grounding pose, foundation of all yoga asanas.",
  },
  {
    name: "Vrikshasana (Tree Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["legs", "core"],
    difficulty: "beginner",
    description: "One-leg balance pose improving focus and stability.",
  },
  {
    name: "Trikonasana (Triangle Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["legs", "core", "shoulders"],
    difficulty: "beginner",
    description: "Side stretch with wide stance engaging the lateral chain.",
  },
  {
    name: "Virabhadrasana I (Warrior I)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "core", "shoulders"],
    difficulty: "beginner",
    description: "Lunging pose with arms raised, building strength and focus.",
  },
  {
    name: "Virabhadrasana II (Warrior II)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "glutes", "core"],
    difficulty: "beginner",
    description: "Wide-stance warrior building hip and leg endurance.",
  },
  {
    name: "Virabhadrasana III (Warrior III)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "core", "glutes"],
    difficulty: "intermediate",
    description:
      "Single-leg balance in T-shape for strength and concentration.",
  },
  {
    name: "Adho Mukha Svanasana (Downward Dog)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "shoulders", "calves", "back"],
    difficulty: "beginner",
    description: "Inverted V-shape stretch for hamstrings and shoulders.",
  },
  {
    name: "Balasana (Child's Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["back", "hips", "shoulders"],
    difficulty: "beginner",
    description: "Restorative resting pose for back and hip release.",
  },
  {
    name: "Bhujangasana (Cobra Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "chest", "core"],
    difficulty: "beginner",
    description: "Prone backbend opening the chest and spine.",
  },
  {
    name: "Setu Bandhasana (Bridge Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["glutes", "hamstrings", "back"],
    difficulty: "beginner",
    description: "Supine hip lift strengthening glutes and lower back.",
  },
  {
    name: "Uttanasana (Standing Forward Bend)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "calves", "back"],
    difficulty: "beginner",
    description: "Fold forward from standing to stretch entire posterior.",
  },
  {
    name: "Paschimottanasana (Seated Forward Bend)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "back"],
    difficulty: "beginner",
    description: "Seated fold targeting hamstrings and lower back.",
  },
  {
    name: "Halasana (Plow Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "hamstrings", "shoulders"],
    difficulty: "intermediate",
    description: "Inverted pose with legs over the head for spine flexibility.",
  },
  {
    name: "Sarvangasana (Shoulder Stand)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "back", "legs"],
    difficulty: "intermediate",
    description:
      "Full inversion on shoulders benefiting thyroid and circulation.",
  },
  {
    name: "Matsyasana (Fish Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["chest", "back", "throat"],
    difficulty: "beginner",
    description: "Supine backbend opening the chest and throat.",
  },
  {
    name: "Ardha Matsyendrasana (Half Spinal Twist)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "core", "hips"],
    difficulty: "beginner",
    description: "Seated spinal twist for spine mobility and digestion.",
  },
  {
    name: "Surya Namaskar (Sun Salutation)",
    type: "flexibility",
    caloriesPerMinute: 5,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "12-posture yoga flow synchronised with breath.",
  },
  {
    name: "Chandra Namaskar (Moon Salutation)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["full body"],
    difficulty: "intermediate",
    description: "Cooling moon-salutation flow with lateral movements.",
  },
  {
    name: "Padmasana (Lotus Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["hips", "knees", "ankles"],
    difficulty: "intermediate",
    description: "Cross-legged meditation seat opening hips.",
  },
  {
    name: "Sukhasana (Easy Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["hips", "groin"],
    difficulty: "beginner",
    description: "Simple crossed-leg seated meditation pose.",
  },
  {
    name: "Vajrasana (Diamond Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["knees", "hips", "ankles"],
    difficulty: "beginner",
    description: "Kneeling meditation seat aiding digestion.",
  },
  {
    name: "Baddha Konasana (Butterfly Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hips", "groin", "inner thighs"],
    difficulty: "beginner",
    description: "Seated pose with soles together flapping knees like wings.",
  },
  {
    name: "Gomukhasana (Cow Face Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hips", "shoulders", "triceps"],
    difficulty: "intermediate",
    description: "Deep hip and shoulder opener in seated position.",
  },
  {
    name: "Garudasana (Eagle Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "shoulders", "core"],
    difficulty: "intermediate",
    description: "Balancing pose with limbs entwined like an eagle.",
  },
  {
    name: "Natarajasana (Dancer Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "back", "core"],
    difficulty: "intermediate",
    description: "Backbend balance on one leg inspired by Shiva's dance.",
  },
  {
    name: "Utkatasana (Chair Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["quadriceps", "glutes", "core"],
    difficulty: "beginner",
    description: "Powerful squat-like pose strengthening the thighs and core.",
  },
  {
    name: "Marjaryasana (Cat Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["back", "core"],
    difficulty: "beginner",
    description: "Spinal flexion on hands and knees for spine mobility.",
  },
  {
    name: "Bitilasana (Cow Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["back", "core"],
    difficulty: "beginner",
    description: "Spinal extension paired with Cat Pose for Cat-Cow flow.",
  },
  {
    name: "Eka Pada Rajakapotasana (Pigeon Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hips", "glutes", "psoas"],
    difficulty: "intermediate",
    description: "Deep hip opener releasing the piriformis and hip flexors.",
  },
  {
    name: "Dhanurasana (Bow Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["back", "chest", "glutes", "quadriceps"],
    difficulty: "intermediate",
    description: "Lying backbend grasping ankles like a drawn bow.",
  },
  {
    name: "Ustrasana (Camel Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["chest", "back", "quadriceps", "hip flexors"],
    difficulty: "intermediate",
    description: "Kneeling deep backbend opening the entire front body.",
  },
  {
    name: "Chakrasana (Wheel Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["chest", "shoulders", "back", "core"],
    difficulty: "advanced",
    description: "Full backbend with hands and feet on the ground.",
  },
  {
    name: "Salabhasana (Locust Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "glutes", "hamstrings"],
    difficulty: "beginner",
    description: "Prone backbend lifting legs and chest off the floor.",
  },
  {
    name: "Sirsasana (Headstand)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "shoulders", "arms"],
    difficulty: "advanced",
    description: "King of asanas – full inversion on crown of head.",
  },
  {
    name: "Parivrtta Trikonasana (Revolved Triangle)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["core", "hamstrings", "back"],
    difficulty: "intermediate",
    description: "Twisted triangle pose for detox and spine rotation.",
  },
  {
    name: "Malasana (Garland Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hips", "groin", "ankles"],
    difficulty: "beginner",
    description: "Deep yogic squat to open hips and ankles.",
  },
  {
    name: "Utthita Parsvakonasana (Extended Side Angle)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "core", "obliques"],
    difficulty: "beginner",
    description: "Wide lunge with extended arm over the ear.",
  },
  {
    name: "Viparita Karani (Legs Up the Wall)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["hamstrings", "back", "legs"],
    difficulty: "beginner",
    description: "Restorative inversion for circulation and relaxation.",
  },
  {
    name: "Savasana (Corpse Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Final relaxation pose for integration and rest.",
  },
  {
    name: "Janu Sirsasana (Head-to-Knee Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "back", "hips"],
    difficulty: "beginner",
    description: "Seated forward fold over one extended leg.",
  },
  {
    name: "Navasana (Boat Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "hip flexors", "quadriceps"],
    difficulty: "intermediate",
    description: "Seated V-shape boat pose for core strength.",
  },
  {
    name: "Chaturanga Dandasana (Four-Limbed Staff Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["chest", "core", "triceps", "shoulders"],
    difficulty: "intermediate",
    description: "Low plank transition pose in Sun Salutation.",
  },
  {
    name: "Urdhva Mukha Svanasana (Upward Facing Dog)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "chest", "core"],
    difficulty: "beginner",
    description: "Prone backbend with straight arms lifting chest and thighs.",
  },
  {
    name: "Dandasana (Staff Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["core", "back", "hamstrings"],
    difficulty: "beginner",
    description: "Seated upright with legs extended — foundation pose.",
  },
  {
    name: "Purvottanasana (Upward Plank)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["glutes", "back", "shoulders", "wrists"],
    difficulty: "intermediate",
    description: "Reverse plank strengthening the posterior chain.",
  },
  {
    name: "Vasisthasana (Side Plank Yoga)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "obliques", "shoulders"],
    difficulty: "intermediate",
    description: "Side plank balancing on one hand and foot.",
  },
  {
    name: "Anjaneyasana (Low Lunge)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hip flexors", "quadriceps", "core"],
    difficulty: "beginner",
    description: "Crescent low lunge for deep hip flexor stretch.",
  },
  {
    name: "Ardha Chandrasana (Half Moon Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "core", "glutes"],
    difficulty: "intermediate",
    description: "Balancing pose on one leg with arms extended laterally.",
  },
  {
    name: "Parivrtta Ardha Chandrasana (Revolved Half Moon)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["legs", "core", "back"],
    difficulty: "advanced",
    description: "Twisted version of half moon for deep torso rotation.",
  },
  {
    name: "Ananda Balasana (Happy Baby Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["hips", "groin", "back"],
    difficulty: "beginner",
    description: "Supine hip opener grasping the feet joyfully.",
  },
  {
    name: "Supta Matsyendrasana (Supine Spinal Twist)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["back", "core", "hips"],
    difficulty: "beginner",
    description: "Gentle spinal twist lying on the back for release.",
  },
  {
    name: "Bakasana (Crow Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["core", "shoulders", "wrists", "arms"],
    difficulty: "advanced",
    description: "Arm-balance with knees resting on upper arms.",
  },
  {
    name: "Pincha Mayurasana (Forearm Stand)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["shoulders", "core", "back"],
    difficulty: "advanced",
    description: "Forearm inversion requiring strong shoulder stability.",
  },
  {
    name: "Adho Mukha Vrksasana (Handstand Yoga)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["shoulders", "core", "wrists"],
    difficulty: "advanced",
    description: "Full handstand balance on the palms.",
  },
  {
    name: "Upavista Konasana (Wide Seated Forward Fold)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "groin", "back"],
    difficulty: "beginner",
    description: "Wide-legged seated forward fold for groin and hamstrings.",
  },
  {
    name: "Mayurasana (Peacock Pose)",
    type: "flexibility",
    caloriesPerMinute: 5,
    muscleGroups: ["core", "wrists", "forearms"],
    difficulty: "advanced",
    description: "Advanced arm balance on elbows with body horizontal.",
  },
  {
    name: "Bharadvajasana (Sage Twist)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "core", "hips"],
    difficulty: "beginner",
    description: "Seated lateral twist named after sage Bharadvaja.",
  },
  {
    name: "Virasana (Hero Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["knees", "quadriceps", "ankles"],
    difficulty: "beginner",
    description: "Kneeling seated pose stretching quads and ankles.",
  },
  {
    name: "Supta Virasana (Reclining Hero Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["quadriceps", "knees", "ankles"],
    difficulty: "intermediate",
    description: "Reclined hero pose for deep quad stretch.",
  },
  {
    name: "Supta Baddha Konasana (Reclining Butterfly)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["hips", "groin", "inner thighs"],
    difficulty: "beginner",
    description: "Supine butterfly releasing hips and inner thighs.",
  },
  {
    name: "Uttana Pristhasana (Lizard Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hip flexors", "groin", "hamstrings"],
    difficulty: "intermediate",
    description: "Deep lunge with forearms lowered for hip opening.",
  },
  {
    name: "Skandasana (Side Lunge Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["hips", "adductors", "hamstrings"],
    difficulty: "intermediate",
    description: "Wide lateral lunge for inner thigh and hip opening.",
  },
  {
    name: "Agnistambhasana (Fire Log Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hips", "glutes", "outer hip"],
    difficulty: "intermediate",
    description: "Stacked shin pose for deep outer hip stretch.",
  },
  {
    name: "Mandukasana (Frog Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hips", "groin", "inner thighs"],
    difficulty: "intermediate",
    description: "Wide-knee prone pose for intense groin opening.",
  },
  {
    name: "Kumbhakasana (Plank Yoga Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["core", "shoulders", "arms"],
    difficulty: "beginner",
    description: "High plank pose building core strength and stability.",
  },
  {
    name: "Parsvottanasana (Pyramid Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "back", "shoulders"],
    difficulty: "intermediate",
    description: "Standing forward fold over front leg with hands behind.",
  },
  {
    name: "Prasarita Padottanasana (Wide-Legged Forward Fold)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "groin", "back"],
    difficulty: "beginner",
    description: "Wide-stance standing forward fold.",
  },
  {
    name: "Uttana Shishosana (Extended Puppy Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["shoulders", "back", "spine"],
    difficulty: "beginner",
    description: "Heart-melting pose between child's pose and downward dog.",
  },
  {
    name: "Parighasana (Gate Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["obliques", "core", "hip flexors"],
    difficulty: "beginner",
    description: "Kneeling side stretch opening the lateral body.",
  },
  {
    name: "Yoga Sun Salutation",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Classic yoga flow linking breath with movement.",
  },
  {
    name: "Hip Flexor Stretch",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hip flexors", "quadriceps"],
    difficulty: "beginner",
    description: "Kneeling lunge stretch to open hip flexors.",
  },
  {
    name: "Hamstring Stretch",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings"],
    difficulty: "beginner",
    description: "Seated or standing stretch for hamstrings.",
  },
  {
    name: "Shavasana Flow (Yoga Nidra)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Guided deep relaxation and body scan practice.",
  },
  {
    name: "Kapalbhati Pranayama",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "diaphragm"],
    difficulty: "beginner",
    description: "Rapid diaphragmatic breathing to energise and cleanse.",
  },
  {
    name: "Anulom Vilom (Alternate Nostril)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["diaphragm"],
    difficulty: "beginner",
    description: "Alternate nostril pranayama balancing energy channels.",
  },
  {
    name: "Bhramari Pranayama (Bee Breath)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["diaphragm"],
    difficulty: "beginner",
    description: "Humming breath calming the nervous system.",
  },
  {
    name: "Ujjayi Pranayama (Ocean Breath)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["diaphragm", "throat"],
    difficulty: "beginner",
    description: "Constricted-throat breathing used throughout vinyasa yoga.",
  },
  {
    name: "Tolasana (Scale Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "wrists", "arms"],
    difficulty: "advanced",
    description: "Arm balance from lotus lifting body off the floor.",
  },
  {
    name: "Tittibhasana (Firefly Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["core", "shoulders", "hamstrings"],
    difficulty: "advanced",
    description: "Arm balance with legs extended parallel to the floor.",
  },
  {
    name: "Marichyasana I (Sage Marichi Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "hamstrings", "core"],
    difficulty: "intermediate",
    description: "Forward fold and bind over one bent knee.",
  },
  {
    name: "Krounchasana (Heron Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "back", "hip flexors"],
    difficulty: "intermediate",
    description: "Seated extended-leg stretch resembling a heron.",
  },
  {
    name: "Kapotasana (King Pigeon Pose)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["chest", "hip flexors", "back"],
    difficulty: "advanced",
    description: "Advanced kneeling backbend grasping the feet.",
  },
  {
    name: "Hanumanasana (Splits / Monkey Pose)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings", "hip flexors", "groin"],
    difficulty: "advanced",
    description: "Full front split named after Hanuman's giant leap.",
  },
  {
    name: "Samakonasana (Straddle Splits)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["groin", "adductors", "hamstrings"],
    difficulty: "advanced",
    description: "Full side split for extreme hip flexibility.",
  },
  {
    name: "Simhasana (Lion Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["face", "throat", "core"],
    difficulty: "beginner",
    description: "Kneeling pose with forceful exhale through wide-open mouth.",
  },
  {
    name: "Kukutasana (Rooster Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["core", "wrists", "arms"],
    difficulty: "advanced",
    description: "Arm balance with arms threaded through lotus legs.",
  },
  {
    name: "Dwi Pada Sirsasana (Two-Leg Behind Head)",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["hips", "hamstrings", "back"],
    difficulty: "advanced",
    description: "Extreme hip opener placing both legs behind the head.",
  },
  {
    name: "Astavakrasana (Eight-Angle Pose)",
    type: "flexibility",
    caloriesPerMinute: 5,
    muscleGroups: ["core", "shoulders", "wrists"],
    difficulty: "advanced",
    description: "Twisted arm balance named after sage Ashtavakra.",
  },
  {
    name: "Eka Pada Koundinyasana (Flying Splits Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["core", "shoulders", "hamstrings"],
    difficulty: "advanced",
    description: "Twisted arm balance with legs split.",
  },
  {
    name: "Parivrtta Utkatasana (Revolved Chair Pose)",
    type: "flexibility",
    caloriesPerMinute: 4,
    muscleGroups: ["core", "obliques", "legs"],
    difficulty: "intermediate",
    description: "Chair pose with a deep spinal twist.",
  },
  {
    name: "Uttana Shishosana II (Heart Melting Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["shoulders", "spine", "chest"],
    difficulty: "beginner",
    description: "Chest to floor shoulder opener for thoracic mobility.",
  },
  {
    name: "Yoga Mudrasana (Yoga Seal)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["back", "shoulders", "hips"],
    difficulty: "intermediate",
    description: "Seated forward fold with hands bound behind the back.",
  },
  {
    name: "Nadi Shodhana Pranayama",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["diaphragm"],
    difficulty: "beginner",
    description: "Channel-purifying pranayama balancing left and right body.",
  },
  {
    name: "Siddhasana (Accomplished Pose)",
    type: "flexibility",
    caloriesPerMinute: 1,
    muscleGroups: ["hips", "groin"],
    difficulty: "intermediate",
    description:
      "Meditation seat with heel at perineum, classic for pranayama.",
  },
  {
    name: "Agneyasana (Fire Pose / Broken Foot Stretch)",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["ankles", "feet", "shins"],
    difficulty: "beginner",
    description: "Kneeling on tops of feet to stretch the shins and ankles.",
  },

  // ── BALANCE (15) ─────────────────────────────────────────────────────────────
  {
    name: "Single Leg Deadlift",
    type: "balance",
    caloriesPerSet: 10,
    muscleGroups: ["hamstrings", "glutes", "core"],
    difficulty: "intermediate",
    description: "Single-leg hinge challenging balance and hip stability.",
  },
  {
    name: "Bosu Ball Squat",
    type: "balance",
    caloriesPerSet: 9,
    muscleGroups: ["quadriceps", "glutes", "core"],
    difficulty: "beginner",
    description: "Squat on a Bosu ball to train proprioception.",
  },
  {
    name: "Single Leg Stand",
    type: "balance",
    caloriesPerMinute: 2,
    muscleGroups: ["core", "ankles", "glutes"],
    difficulty: "beginner",
    description: "Stand on one leg with progressions (eyes closed, surface).",
  },
  {
    name: "Pistol Squat",
    type: "balance",
    caloriesPerSet: 14,
    muscleGroups: ["quadriceps", "glutes", "core"],
    difficulty: "advanced",
    description: "Full single-leg squat requiring strength and coordination.",
  },
  {
    name: "Stability Ball Plank",
    type: "balance",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "shoulders"],
    difficulty: "intermediate",
    description: "Plank with hands or feet on a stability ball.",
  },
  {
    name: "Balance Board Training",
    type: "balance",
    caloriesPerMinute: 4,
    muscleGroups: ["ankles", "core", "legs"],
    difficulty: "beginner",
    description: "Standing or squatting on a wobble/balance board.",
  },
  {
    name: "Bird Dog",
    type: "balance",
    caloriesPerMinute: 3,
    muscleGroups: ["core", "glutes", "back"],
    difficulty: "beginner",
    description:
      "Opposite arm-leg extension from all-fours for core stability.",
  },
  {
    name: "Side Plank",
    type: "balance",
    caloriesPerMinute: 3,
    muscleGroups: ["obliques", "core", "shoulders"],
    difficulty: "intermediate",
    description: "Lateral plank hold for oblique and hip stability.",
  },
  {
    name: "Heel-to-Toe Walk",
    type: "balance",
    caloriesPerMinute: 2,
    muscleGroups: ["core", "ankles", "legs"],
    difficulty: "beginner",
    description: "Tightrope-style walking for proprioception.",
  },
  {
    name: "Bosu Push-Up",
    type: "balance",
    caloriesPerSet: 9,
    muscleGroups: ["chest", "core", "triceps"],
    difficulty: "intermediate",
    description: "Push-up on dome side of Bosu ball for instability challenge.",
  },
  {
    name: "Skater Balance",
    type: "balance",
    caloriesPerMinute: 4,
    muscleGroups: ["glutes", "core", "legs"],
    difficulty: "intermediate",
    description: "Lateral skater leaps developing explosive balance.",
  },
  {
    name: "Single Leg Calf Raise",
    type: "balance",
    caloriesPerSet: 5,
    muscleGroups: ["calves", "ankles"],
    difficulty: "beginner",
    description: "One-leg calf raise for ankle stability and strength.",
  },
  {
    name: "Tandem Stance Hold",
    type: "balance",
    caloriesPerMinute: 1,
    muscleGroups: ["core", "ankles"],
    difficulty: "beginner",
    description: "Heel-to-toe tandem standing for balance rehabilitation.",
  },
  {
    name: "Tai Chi (flowing form)",
    type: "balance",
    caloriesPerMinute: 3,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Slow meditative martial art for balance and mindfulness.",
  },
  {
    name: "Slackline Walking",
    type: "balance",
    caloriesPerMinute: 4,
    muscleGroups: ["core", "ankles", "legs"],
    difficulty: "intermediate",
    description: "Walking on a slackline for extreme proprioceptive training.",
  },

  // ── FUNCTIONAL (20) ──────────────────────────────────────────────────────────
  {
    name: "Burpees",
    type: "functional",
    caloriesPerMinute: 11,
    muscleGroups: ["full body"],
    difficulty: "intermediate",
    description:
      "Full-body explosive movement combining squat thrust and jump.",
  },
  {
    name: "Kettlebell Swing",
    type: "functional",
    caloriesPerMinute: 12,
    muscleGroups: ["glutes", "hamstrings", "back", "core"],
    difficulty: "intermediate",
    description: "Hip-driven ballistic swing with a kettlebell.",
  },
  {
    name: "Box Jumps",
    type: "functional",
    caloriesPerSet: 14,
    muscleGroups: ["quadriceps", "glutes", "calves"],
    difficulty: "intermediate",
    description: "Explosive plyometric jump onto a box.",
  },
  {
    name: "Battle Ropes",
    type: "functional",
    caloriesPerMinute: 10,
    muscleGroups: ["shoulders", "core", "back"],
    difficulty: "intermediate",
    description: "Heavy rope waves for conditioning and shoulder endurance.",
  },
  {
    name: "Turkish Get-Up",
    type: "functional",
    caloriesPerMinute: 5,
    muscleGroups: ["full body", "core", "shoulders"],
    difficulty: "advanced",
    description: "Full-body ground-to-stand movement with a kettlebell.",
  },
  {
    name: "Farmer's Carry",
    type: "functional",
    caloriesPerMinute: 8,
    muscleGroups: ["traps", "core", "grip", "legs"],
    difficulty: "beginner",
    description: "Loaded carry for grip, posture and total-body stability.",
  },
  {
    name: "Medicine Ball Slam",
    type: "functional",
    caloriesPerMinute: 10,
    muscleGroups: ["core", "shoulders", "back"],
    difficulty: "intermediate",
    description: "Overhead slam for power and stress release.",
  },
  {
    name: "Sled Push",
    type: "functional",
    caloriesPerMinute: 14,
    muscleGroups: ["legs", "core", "glutes"],
    difficulty: "intermediate",
    description:
      "Pushing a weighted sled for explosive lower body conditioning.",
  },
  {
    name: "Wall Ball",
    type: "functional",
    caloriesPerMinute: 10,
    muscleGroups: ["legs", "shoulders", "core"],
    difficulty: "intermediate",
    description: "Squat-to-throw against a wall with a medicine ball.",
  },
  {
    name: "Dumbbell Thruster",
    type: "functional",
    caloriesPerMinute: 11,
    muscleGroups: ["legs", "shoulders", "core"],
    difficulty: "intermediate",
    description: "Front squat to overhead press in one fluent movement.",
  },
  {
    name: "Kettlebell Clean and Press",
    type: "functional",
    caloriesPerMinute: 10,
    muscleGroups: ["shoulders", "core", "legs", "back"],
    difficulty: "intermediate",
    description: "Clean to rack position then press overhead.",
  },
  {
    name: "Bear Crawl",
    type: "functional",
    caloriesPerMinute: 8,
    muscleGroups: ["core", "shoulders", "legs"],
    difficulty: "beginner",
    description: "Crawling on hands and feet for total-body stability.",
  },
  {
    name: "Sandbag Carry",
    type: "functional",
    caloriesPerMinute: 9,
    muscleGroups: ["traps", "core", "legs"],
    difficulty: "intermediate",
    description: "Loaded sandbag carry mimicking real-world lifting.",
  },
  {
    name: "Rope Climb",
    type: "functional",
    caloriesPerMinute: 10,
    muscleGroups: ["back", "biceps", "core", "grip"],
    difficulty: "advanced",
    description: "Climb a hanging rope using arms and legs.",
  },
  {
    name: "Power Clean",
    type: "functional",
    caloriesPerMinute: 11,
    muscleGroups: ["full body", "traps", "legs", "back"],
    difficulty: "advanced",
    description: "Olympic lift pulling the bar from floor to front rack.",
  },
  {
    name: "Handstand Push-Up",
    type: "functional",
    caloriesPerSet: 12,
    muscleGroups: ["shoulders", "core", "triceps"],
    difficulty: "advanced",
    description: "Inverted push-up against a wall for vertical pressing power.",
  },
  {
    name: "Prowler Sprint",
    type: "functional",
    caloriesPerMinute: 15,
    muscleGroups: ["legs", "glutes", "core"],
    difficulty: "advanced",
    description: "Explosive sprint pushing a loaded Prowler sled.",
  },
  {
    name: "Tire Flip",
    type: "functional",
    caloriesPerMinute: 12,
    muscleGroups: ["back", "legs", "shoulders", "core"],
    difficulty: "advanced",
    description:
      "Dead-lift and flip a large tractor tyre for total-body power.",
  },
  {
    name: "Ring Rows",
    type: "functional",
    caloriesPerSet: 9,
    muscleGroups: ["back", "biceps", "core"],
    difficulty: "beginner",
    description:
      "Horizontal pull on gymnastic rings for scalable row strength.",
  },
  {
    name: "Plyometric Lunge Jump",
    type: "functional",
    caloriesPerMinute: 12,
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    difficulty: "intermediate",
    description: "Explosive alternating lunge jump for power and agility.",
  },

  {
    name: "Cycling (stationary)",
    type: "cardio",
    caloriesPerMinute: 8,
    muscleGroups: ["quadriceps", "glutes", "calves"],
    difficulty: "beginner",
    description: "Low-impact cardio on stationary bike.",
  },
  {
    name: "Jump Rope",
    type: "cardio",
    caloriesPerMinute: 12,
    muscleGroups: ["calves", "core", "shoulders"],
    difficulty: "intermediate",
    description: "High-intensity skipping rope workout.",
  },
  {
    name: "Swimming (laps)",
    type: "cardio",
    caloriesPerMinute: 9,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Full body low-impact cardio in the pool.",
  },
  {
    name: "HIIT Sprint Intervals",
    type: "cardio",
    caloriesPerMinute: 14,
    muscleGroups: ["quadriceps", "hamstrings", "glutes"],
    difficulty: "advanced",
    description: "Alternating high-intensity sprints with short rest periods.",
  },
  {
    name: "Walking (brisk)",
    type: "cardio",
    caloriesPerMinute: 5,
    muscleGroups: ["glutes", "hamstrings", "calves"],
    difficulty: "beginner",
    description: "Brisk walking, excellent for beginners and active recovery.",
  },
  {
    name: "Elliptical Trainer",
    type: "cardio",
    caloriesPerMinute: 7,
    muscleGroups: ["quadriceps", "glutes", "core"],
    difficulty: "beginner",
    description: "Low-impact full body cardio machine.",
  },
  {
    name: "Rowing Machine",
    type: "cardio",
    caloriesPerMinute: 11,
    muscleGroups: ["back", "biceps", "core", "glutes"],
    difficulty: "intermediate",
    description: "Full body cardio on the rowing machine.",
  },
  // STRENGTH
  {
    name: "Barbell Back Squat",
    type: "strength",
    caloriesPerSet: 20,
    muscleGroups: ["quadriceps", "glutes", "hamstrings", "core"],
    difficulty: "intermediate",
    description:
      "The king of lower body exercises. Barbell on upper back, squat to parallel.",
  },
  {
    name: "Deadlift",
    type: "strength",
    caloriesPerSet: 22,
    muscleGroups: ["back", "glutes", "hamstrings", "core"],
    difficulty: "intermediate",
    description: "Hinge-pattern lift engaging the entire posterior chain.",
  },
  {
    name: "Bench Press",
    type: "strength",
    caloriesPerSet: 15,
    muscleGroups: ["chest", "triceps", "shoulders"],
    difficulty: "intermediate",
    description: "Horizontal push on a flat bench with barbell or dumbbells.",
  },
  {
    name: "Pull Ups",
    type: "strength",
    caloriesPerSet: 12,
    muscleGroups: ["back", "biceps", "core"],
    difficulty: "intermediate",
    description:
      "Bodyweight vertical pull. Excellent for back and arm development.",
  },
  {
    name: "Overhead Press",
    type: "strength",
    caloriesPerSet: 14,
    muscleGroups: ["shoulders", "triceps", "core"],
    difficulty: "intermediate",
    description: "Standing barbell press overhead.",
  },
  {
    name: "Dumbbell Lunges",
    type: "strength",
    caloriesPerSet: 10,
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    difficulty: "beginner",
    description: "Walking or stationary lunges holding dumbbells.",
  },
  {
    name: "Dumbbell Bicep Curl",
    type: "strength",
    caloriesPerSet: 7,
    muscleGroups: ["biceps"],
    difficulty: "beginner",
    description: "Isolation curl for the biceps muscle.",
  },
  {
    name: "Tricep Dips",
    type: "strength",
    caloriesPerSet: 9,
    muscleGroups: ["triceps", "chest", "shoulders"],
    difficulty: "beginner",
    description: "Bodyweight dips on parallel bars or a bench.",
  },
  {
    name: "Bent Over Row",
    type: "strength",
    caloriesPerSet: 16,
    muscleGroups: ["back", "biceps", "core"],
    difficulty: "intermediate",
    description: "Barbell or dumbbell row for mid-back development.",
  },
  {
    name: "Romanian Deadlift",
    type: "strength",
    caloriesPerSet: 18,
    muscleGroups: ["hamstrings", "glutes", "back"],
    difficulty: "intermediate",
    description:
      "Hip-hinge focusing on hamstring stretch and glute activation.",
  },
  {
    name: "Bulgarian Split Squat",
    type: "strength",
    caloriesPerSet: 15,
    muscleGroups: ["quadriceps", "glutes", "hamstrings"],
    difficulty: "advanced",
    description: "Rear-elevated split squat for single-leg strength.",
  },
  // FLEXIBILITY
  {
    name: "Yoga Sun Salutation",
    type: "flexibility",
    caloriesPerMinute: 3,
    muscleGroups: ["full body"],
    difficulty: "beginner",
    description: "Classic yoga flow linking breath with movement.",
  },
  {
    name: "Hip Flexor Stretch",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["glutes", "quadriceps"],
    difficulty: "beginner",
    description: "Kneeling lunge stretch to open hip flexors.",
  },
  {
    name: "Hamstring Stretch",
    type: "flexibility",
    caloriesPerMinute: 2,
    muscleGroups: ["hamstrings"],
    difficulty: "beginner",
    description: "Seated or standing stretch targeting the hamstrings.",
  },
  // FUNCTIONAL
  {
    name: "Burpees",
    type: "functional",
    caloriesPerMinute: 11,
    muscleGroups: ["full body"],
    difficulty: "intermediate",
    description:
      "Full body explosive movement combining squat thrust and jump.",
  },
  {
    name: "Kettlebell Swing",
    type: "functional",
    caloriesPerSet: 12,
    muscleGroups: ["glutes", "hamstrings", "back", "core"],
    difficulty: "intermediate",
    description: "Hip-driven swing with kettlebell, ballistic in nature.",
  },
  {
    name: "Box Jumps",
    type: "functional",
    caloriesPerSet: 14,
    muscleGroups: ["quadriceps", "glutes", "calves"],
    difficulty: "intermediate",
    description: "Explosive plyometric jump onto a box or platform.",
  },
  {
    name: "Battle Ropes",
    type: "functional",
    caloriesPerMinute: 10,
    muscleGroups: ["shoulders", "core", "back"],
    difficulty: "intermediate",
    description:
      "Heavy rope waves — great for conditioning and shoulder endurance.",
  },
  // BALANCE
  {
    name: "Single Leg Deadlift",
    type: "balance",
    caloriesPerSet: 10,
    muscleGroups: ["hamstrings", "glutes", "core"],
    difficulty: "intermediate",
    description:
      "Single-leg hinge pattern that challenges balance and stability.",
  },
  {
    name: "Bosu Ball Squat",
    type: "balance",
    caloriesPerSet: 9,
    muscleGroups: ["quadriceps", "glutes", "core"],
    difficulty: "beginner",
    description: "Squat on a Bosu ball to challenge proprioception.",
  },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB");

  let added = 0;
  let skipped = 0;

  for (const ex of exercises) {
    const exists = await Exercise.findOne({
      name: { $regex: `^${ex.name}$`, $options: "i" },
    });
    if (exists) {
      skipped++;
      continue;
    }
    await Exercise.create({ ...ex, verification: { verified: true } });
    added++;
  }

  console.log(`✅ Seeded: ${added} added, ${skipped} already existed`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
